### ISSUE TITLE
Add `Ci/Cd` github actions for checking dotnet code

### ISSUE THREAD

**Issue by taha-ghadirian** [Evie-Skinner18/LaFromagerie#10]
Hello dear maintainers, adding an new **github workflow** to this project, will help us for better and faster improvement. 

Suggested scenarios:

- Automated unit tests
- Automated code style check
- Automatically build tests
- Automated check application health on `Windows server 2022/2019/2016` and `Ubuntu Linux` and `macos-10.15`.

I can also work on this issue if you want.

**Comment by Evie-Skinner18** [comment]
thank @taha-ghadirian  you legend. Go ahead!
