### ISSUE TITLE
Implement a facade pattern

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/LaFromagerie#4]
- In CheeseShopLogic, add some business logic using a facade pattern
- Ensure it works alongside the other business logic and patterns
- Add some code to the console app UI to consume your new logic

Happy coding!

**Comment by nickyg91** [comment]
I'd like to tackle this one - you can assign this one to me!

**Comment by Evie-Skinner18** [comment]
Enjoy!
