### ISSUE TITLE
Implement a decorator pattern

### ISSUE THREAD

**Issue by Evie-Skinner18** [Evie-Skinner18/LaFromagerie#5]
-     In CheeseShopLogic, add some business logic using a decorator pattern
-     Ensure it works alongside the other business logic and patterns
-     Add some code to the console app UI to consume your new logic

Happy coding!

**Comment by nico91470** [comment]
Hello, I want to try to resolve this issue. Can you assign it to me?

**Comment by Evie-Skinner18** [comment]
Hiya! Absolutely. Will assign to you and mark the issue as 'in progress'

**Comment by nico91470** [comment]
I want to implement Decorator pattern on "Cheese" with multiple chees variety:

- Saint-nectaire
- Comte
- Camembert

and to add multiple decorator like:
- 6 month
- 12 month
- Pepper
- Nuts

Do you think it's a good idea?

**Comment by Evie-Skinner18** [comment]
Hi @nico91470 , yes great idea. Can't wait to see what you produce. Feel free to remove some of the comments I've left there aswell!
