### ISSUE TITLE
Upgrade to `Dotnet 5/6`

### ISSUE THREAD

**Issue by taha-ghadirian** [Evie-Skinner18/LaFromagerie#8]
Hello dear managers, 
Could I upgrade this project to dotnet 5 or 6? 
I think it have better performance by the way.

**Comment by Evie-Skinner18** [comment]
Hi @taha-ghadirian ! Thanks very much for the suggestion. Would prefer to keep this .Net Core so Mac/Linux users (including me) can continue to participate. You can maybe upgrade to the latest .Net Core?

**Comment by taha-ghadirian** [comment]
> Hi @taha-ghadirian ! Thanks very much for the suggestion. Would prefer to keep this .Net Core so Mac/Linux users (including me) can continue to participate. You can maybe upgrade to the latest .Net Core?

Yes of course I can, `Dotnet 5` is the latest LTS version of `Dotnet core`, and `Dotnet 6` is the beta one. 
Dotnet 6 has more futures and more performance, but its still on beta version and under test. 

in both version, project can run and compile in mac/windows/linux as well as other dotnet core versions (Included dotnet 3). 

So for making PR ready, could you tell me ,with this information, which version of new dotnets are more preferable for you and project? (More **stable**, or more **futures**?)

**Comment by Evie-Skinner18** [comment]
Thanks for explaining that! In that case let's go wild and upgrade to .Net 6 😛

**Comment by taha-ghadirian** [comment]
> Thanks for explaining that! In that case let's go wild and upgrade to .Net 6 😛

Ok 🙂 I'm too happy that I'm working on this project. 
Hope I could do my best :)

Status: Done, PR #9...
